import prisma from '../lib/prisma';
import { getAIProvider } from './aiProviderImpl';
import { hashObject } from '../utils/hash';
import { writeAuditLog } from '../services/auditService';
import { uploadDocument } from '../services/documentService';

export interface AgentConfig {
  name: string;
  systemPrompt: string;
  internalOnly?: boolean;
  requiresManualEntry?: boolean;
}

export abstract class BaseAgent {
  abstract config: AgentConfig;

  async run(taskId: string, stage: number, editorInstructions?: string) {
    const task = await prisma.task.findUnique({ where: { id: taskId } });
    if (!task) throw new Error('Task not found');

    if (this.config.requiresManualEntry && !task.manualEntry) {
      throw new Error('Governance agent requires manual Editor/Admin entry');
    }

    const kbEntries = await prisma.knowledgeBase.findMany({
      where: { domain: task.domain, isActive: true, jurisdiction: 'India' },
      take: 5,
    });

    const ragContext = kbEntries
      .map((kb) => `[${kb.docType}] ${kb.title}: ${kb.content.slice(0, 500)}`)
      .join('\n\n');

    const start = Date.now();
    const provider = getAIProvider();

    const userPrompt = `Task: ${task.title}
Description: ${task.description}
Jurisdiction: India — apply Indian law only
Stage: L${stage}
Editor Instructions: ${editorInstructions || 'None'}

Knowledge Base Context:
${ragContext}`;

    const response = await provider.complete({
      systemPrompt: this.config.systemPrompt,
      userPrompt,
    });

    let content = response.content;
    if (this.config.internalOnly) {
      if (!content.includes('FOR INTERNAL USE ONLY') && !content.includes('FOR INTERNAL PREPARATION ONLY')) {
        content = `FOR INTERNAL USE ONLY — DO NOT SEND EXTERNALLY\n\n${content}`;
      }
    }

    const inputHash = hashObject({ taskId, stage, editorInstructions });
    const outputHash = hashObject({ draftContent: content, riskScore: response.riskScore, confidenceScore: response.confidenceScore });

    await prisma.agentLog.create({
      data: {
        taskId,
        agentName: this.config.name,
        stage,
        action: `Generated draft and analysis at L${stage}`,
        inputHash,
        outputHash,
        modelVersion: response.modelVersion,
        ragSources: response.ragSources,
        confidenceScore: response.confidenceScore,
        tokenCount: response.tokenCount,
        durationMs: Date.now() - start,
      },
    });

    await writeAuditLog({
      eventType: 'AI_DRAFT_GENERATED',
      taskId,
      description: `${this.config.name} generated draft at L${stage}`,
      metadata: {
        agentName: this.config.name,
        riskScore: response.riskScore,
        confidenceScore: response.confidenceScore,
        internalOnly: this.config.internalOnly ?? false,
      },
    });

    if (response.complianceNotes.length > 0) {
      await writeAuditLog({
        eventType: 'AI_COMPLIANCE_CHECK',
        taskId,
        description: `${this.config.name} compliance check completed`,
        metadata: { notes: response.complianceNotes },
      });
    }

    const filename = `${task.title.replace(/\s+/g, '_')}_Draft.txt`;
    await uploadDocument({
      taskId,
      filename,
      buffer: Buffer.from(content, 'utf-8'),
      mimeType: 'text/plain',
      uploadedBy: 'SYSTEM',
      notes: `Auto-generated by ${this.config.name} at L${stage}`,
    });

    return {
      content,
      riskScore: response.riskScore,
      ragSources: response.ragSources,
      complianceNotes: response.complianceNotes,
      riskFlags: response.riskFlags,
      recommendedNextStage: response.recommendedNextStage,
      confidenceScore: response.confidenceScore,
      internalOnly: this.config.internalOnly ?? false,
    };
  }
}
