export const SEED_DRAFTS: Record<string, string> = {
  'Vendor MSA Review': `MASTER SERVICES AGREEMENT — DRAFT v1.0
Generated by CoSora contractAgent | Stage L2 → L3

PARTIES:
  Provider: [Vendor Name Ltd.]
  Client:   [Your Company Pvt. Ltd.]

1. SERVICES
   Provider shall deliver professional IT services as described in Exhibit A,
   including software development, maintenance, and support.

2. TERM
   Initial term of 24 months, auto-renewing for successive 12-month periods
   unless terminated with 90 days written notice.

3. FEES & PAYMENT
   Monthly fee of INR 15,00,000 plus applicable taxes. Invoices payable
   within 30 days of receipt.

4. CONFIDENTIALITY
   Each party shall protect the other's Confidential Information for 3 years
   post-termination per standard NDA terms.

5. INDEMNIFICATION
   Provider indemnifies Client against third-party IP infringement claims
   arising from deliverables. Liability cap: 12 months' fees.

6. LIMITATION OF LIABILITY
   Neither party liable for indirect/consequential damages. Aggregate cap:
   fees paid in preceding 12 months.

7. GOVERNING LAW
   Laws of India; courts of Mumbai have exclusive jurisdiction.

⚠ EDITOR REVIEW REQUIRED — Key flags:
   • Liability cap may be insufficient for enterprise risk profile
   • Auto-renewal clause needs 60-day notice (internal policy)
   • IP assignment clause missing from Exhibit A`,

  'GDPR Compliance Audit': `DATA PRIVACY IMPACT ASSESSMENT — DRAFT
Generated by CoSora privacyAgent | DPDP + GDPR

PROCESSING ACTIVITY: Customer analytics platform
DATA CATEGORIES: Name, email, usage logs, IP address
LEGAL BASIS: Legitimate interest / Consent (Art. 6 GDPR)

COMPLIANCE FINDINGS:
  ✓ Privacy notice updated Q1 2024
  ✗ Cross-border transfer mechanism not documented
  ✗ Data retention schedule exceeds 24-month policy
  ⚠ DPDP Act consent framework requires refresh

RECOMMENDED ACTIONS:
  1. Implement Standard Contractual Clauses for EU transfers
  2. Reduce retention to 18 months for usage logs
  3. Deploy consent management platform update`,

  'Employment Termination': `EMPLOYMENT SEPARATION AGREEMENT — DRAFT
Generated by CoSora employmentAgent

EMPLOYEE: [Redacted — Senior Manager]
TERMINATION DATE: [Date]
SEVERANCE: 6 months base salary + accrued leave encashment

KEY TERMS:
  • Mutual release of claims
  • 12-month non-solicitation of employees
  • Return of company property within 5 business days
  • Confidentiality obligations survive termination

STATUTORY COMPLIANCE:
  ✓ Industrial Disputes Act notice period satisfied
  ✓ Payment of gratuity per Payment of Gratuity Act
  ⚠ Non-compete clause requires jurisdiction review`,

  'Patent Filing Review': `PATENT APPLICATION REVIEW MEMO — DRAFT
Generated by CoSora ipAgent

INVENTION: Adaptive machine learning inference optimisation
INVENTORS: [Engineering Team]
JURISDICTION: India (Form 1) + PCT extension recommended

PRIOR ART SEARCH:
  • US Patent 10,XXX,XXX — partial overlap on caching layer
  • EP 3,XXX,XXX — distinct claims on model compression

RECOMMENDATION: Proceed with filing; narrow claims 3 and 7`,

  'Board Resolution Draft': `BOARD RESOLUTION — DRAFT
Generated by CoSora governanceAgent

RESOLVED THAT the Board of Directors approves:
  (a) Appointment of Ms. [Name] as Independent Director
  (b) Authorisation for CFO to execute banking mandates
  (c) Adoption of revised Related Party Transaction Policy

Effective date: [Board Meeting Date]
Quorum: Present per Companies Act 2013 requirements`,

  'Acquisition Due Diligence': `M&A DUE DILIGENCE CHECKLIST — DRAFT
Generated by CoSora maAgent

TARGET: [TargetCo Ltd.]
TRANSACTION VALUE: INR 450 Cr (estimated)

LEGAL DD STATUS:
  □ Corporate structure and cap table verified
  □ Material contracts (top 20) under review
  □ Litigation search — 2 pending labour disputes
  □ Regulatory approvals — CCI notification required
  □ IP portfolio — 14 patents, 8 trademarks

RISK RATING: 5/5 — Escalation recommended`,

  'Regulatory Inquiry Response': `REGULATORY RESPONSE PREPARATION — DRAFT
FOR INTERNAL PREPARATION ONLY — DO NOT SEND EXTERNALLY

Generated by CoSora regulatorAgent

INQUIRY REF: SEBI/2024/[Ref]
SUBJECT: Disclosure compliance query re: Q3 financial statements

DRAFT RESPONSE FRAMEWORK:
  1. Acknowledge receipt within 7 business days
  2. Request 14-day extension for document compilation
  3. Attach revised disclosure schedule with footnotes
  4. Internal review by Compliance + External counsel

⚠ All external communication requires General Counsel approval`,

  'Office Lease Renewal': `COMMERCIAL LEASE REVIEW — DRAFT
Generated by CoSora propertyAgent

PREMISES: [Office Address], Bangalore
CURRENT RENT: INR 2,85,000/month
PROPOSED RENT: INR 3,12,000/month (+9.5% escalation)

KEY TERMS FOR NEGOTIATION:
  • Reduce security deposit from 6 to 4 months
  • Cap annual escalation at 5%
  • Include early termination after 36 months (6-month penalty)
  • Landlord maintenance obligations for HVAC`,

  'Litigation Strategy Memo': `INTERNAL LITIGATION BRIEF — DRAFT
FOR INTERNAL USE ONLY — DO NOT SEND EXTERNALLY

Generated by CoSora litigationAgent

CASE: Commercial dispute — breach of supply agreement
COUNTERPARTY: [Supplier Ltd.]
CLAIM VALUE: INR 2.1 Cr

STRATEGY SUMMARY:
  • Strong documentary evidence of delivery failures
  • Consider mediation before formal proceedings
  • Limitation period: 18 months remaining
  • Reserve provision recommended: INR 85 lakhs

⚠ No external communication without GC sign-off`,

  'Anti-Bribery Policy Update': `CORPORATE POLICY — ANTI-BRIBERY & CORRUPTION
Generated by CoSora policyAgent | v2.1 DRAFT

1. PURPOSE
   Zero tolerance for bribery, facilitation payments, and corrupt practices.

2. SCOPE
   All employees, contractors, agents, and third-party representatives globally.

3. GIFTS & HOSPITALITY
   • Threshold: INR 5,000 per occasion without pre-approval
   • Government officials: absolute prohibition

4. DUE DILIGENCE
   Enhanced screening for agents in high-risk jurisdictions.

5. REPORTING
   Confidential whistleblower hotline; non-retaliation guarantee.

AWAITING L7 LEGAL SIGN-OFF`,
};

export function getDraftForTask(title: string, domain: string): string {
  if (SEED_DRAFTS[title]) return SEED_DRAFTS[title];

  return `${title.toUpperCase()} — AI GENERATED DRAFT
Generated by CoSora automation system

Domain: ${domain.replace(/_/g, ' ')}
Status: Draft for internal review

This document was auto-generated based on task intake data and knowledge base
references. Editor review and HITL approval required before external use.

[Draft content placeholder — run contractAgent for full generation]`;
}

export const AGENT_FOR_DOMAIN: Record<string, string> = {
  CONTRACT_MANAGEMENT: 'contractAgent',
  LEGAL_COMPLIANCE: 'complianceAgent',
  LITIGATION: 'litigationAgent',
  IP_MANAGEMENT: 'ipAgent',
  EMPLOYMENT_LABOUR: 'employmentAgent',
  CORPORATE_GOVERNANCE: 'governanceAgent',
  MERGERS_ACQUISITIONS: 'maAgent',
  DATA_PRIVACY: 'privacyAgent',
  RISK_MANAGEMENT: 'riskAgent',
  REGULATOR_LIAISON: 'regulatorAgent',
  POLICY_DRAFTING: 'policyAgent',
  PROPERTY_LEASING: 'propertyAgent',
};
