'use client';

import { FileText, Download } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api';

interface DocumentPanelProps {
  taskId: string;
  readOnly?: boolean;
  documents?: Array<{
    id: string;
    filename: string;
    version: number;
    isLatest: boolean;
    createdAt: string;
    sha256Hash: string;
  }>;
}

export function DocumentPanel({ taskId, documents, readOnly = false }: DocumentPanelProps) {
  const latest = documents?.find((d) => d.isLatest) || documents?.[0];

  const { data: preview, isLoading } = useQuery({
    queryKey: ['document-preview', taskId],
    queryFn: async () => (await api.get(`/documents/task/${taskId}/preview`)).data,
    enabled: !!taskId,
  });

  const content = preview?.content;
  const doc = preview?.document || latest;

  const download = async () => {
    if (!doc?.id) return;
    const res = await api.get(`/documents/${doc.id}`, { responseType: 'blob' });
    const url = URL.createObjectURL(res.data);
    const a = document.createElement('a');
    a.href = url;
    a.download = doc.filename || 'document.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="cosora-card overflow-hidden">
      <div className="flex items-center justify-between px-4 py-3 border-b border-cosora-smoke bg-cosora-smoke/30">
        <div className="flex items-center gap-2">
          <FileText size={18} className="text-cosora-orange" />
          <h3 className="text-cosora-light font-medium text-sm">Document / Draft</h3>
        </div>
        {doc && !readOnly && (
          <div className="flex items-center gap-3">
            <span className="text-cosora-gold text-xs">v{doc.version}</span>
            <button
              onClick={download}
              className="flex items-center gap-1 text-cosora-mid hover:text-cosora-orange text-xs"
            >
              <Download size={14} /> Download
            </button>
          </div>
        )}
        {doc && readOnly && (
          <span className="text-cosora-gold text-xs">v{doc.version} · View only</span>
        )}
      </div>

      {isLoading ? (
        <div className="p-6 text-cosora-mid text-sm animate-pulse">Loading document...</div>
      ) : !doc ? (
        <div className="p-6 text-cosora-mid text-sm">
          No document generated yet. Run the AI agent to create a draft.
        </div>
      ) : (
        <>
          <div className="px-4 py-2 border-b border-cosora-smoke flex flex-wrap gap-3 text-xs text-cosora-mid">
            <span>{doc.filename}</span>
            <span className="font-mono truncate max-w-[200px]" title={doc.sha256Hash}>
              SHA-256: {doc.sha256Hash?.slice(0, 12)}…
            </span>
            {preview?.generatedBy && (
              <span className="text-cosora-gold">Generated by {preview.generatedBy}</span>
            )}
          </div>
          <div className="p-4 bg-cosora-black max-h-[480px] overflow-y-auto">
            <pre className="font-mono text-sm text-cosora-light whitespace-pre-wrap leading-relaxed">
              {content || 'Document content unavailable.'}
            </pre>
          </div>
        </>
      )}
    </div>
  );
}
